### ISSUE TITLE
Hi, Can you add .bat File type to add program for run as services?

### ISSUE THREAD

**Issue by mashna1364** [devowl/winservicemanager#1]
Hi, Can you add .bat File type to add program for run as services? Please do it , iwant add a program to run as a service but it file type is .bat . and your software support only .exe files

**Comment by devowl** [comment]
Hey there, i can unlock select file type, but i don't sure service can be running as bat file

**Comment by mashna1364** [comment]
Thank you sir, i check it and .bat file is working as a service, please Unlock it

**Comment by devowl** [comment]
I will do it this evening then

**Comment by mashna1364** [comment]
Thank you sir , i waiting you

**Comment by devowl** [comment]
I have updated open code, you check it out

**Comment by mashna1364** [comment]
Thank you sir
